APDL package to do list

* Priorities
1) Makefile(s), Texinfo, TAGS, version strings
2) add lexical binding to create_keywords
3) -mode-update -> -update in -initialise.el
4) Check Github source package with package-install-from-file/buffer
   - apdl-24.0.1.tar.gz, when I remove the "pax_global_header" from
     the github archive we can install it with
     package-install-from-file
   - It seems that package.el is reading the apdl-readme.txt?!
   - package.el needs a <name>.el file
   - manual: tar -cvf apdl-24.0.1.tar *el --transform 's,^,apdl-24.0.1/,'
5) How to place release comments (currently only git logs, NEWS.org?)
6) Texinfo
   - .info binary in repo?
7) Melpa
   - standards
   - <NAME>-pgk.el -> <NAME>.el for summary line and headers
8) Rework qr-code on ansys+emacs.png (or cut it out)

* Images, binaries
** Formatting
Github doesn't (yet) understand org-mode attr_html: and #+caption:
[2025-12-24 Mi]

** Storage
Github copilot suggests storing images directly into repo, when the
images are few and don't change often. Alternatives are
- git-lfs
- github pages

* Work
- Gnu coding standards https://www.gnu.org/prep/standards/
- Makefile conventions? (Magit example)
- TAGS for emacs replacing version strings
- Elisp checks: https://drewsh.com/emacs-package-github-workflow

* Texinfo
We do not need a directory file "dir", we have to place the
apdl.info/apdl.texi (see Melpa build scripts) file in the apdl content
folder.

* Melpa
stores (unstable) packages on melpa.org/packages

- Melpa is supposed to build info files from .texi files?
** checks
https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org

- compiling
- 

- check recipe locally in the cloned melpa archive
  - C-c C-c in recipe/<pkg_name>

** recipie, forked melpa with magit forge
- ~/apdl-mode2/melpa/apdl
- forked repo: ~/melpa

* Release proceedures
- Push to upstream / origin
- Tag (lightweight suffices) e.g. "v25.0.0" creates a release, it
  reads from RELEASE_NOTES.org
- Push tag



# ##############################
# Local Variables:
# minor-mode: flycheck
# indicate-empty-lines: t
# show-trailing-whitespace: t
# End:
